SET SERVEROUTPUT ON;

CREATE TABLE debug_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    module_name  VARCHAR2(100),
    line_no      NUMBER,
    log_level    VARCHAR2(10) DEFAULT 'INFO' NOT NULL,
    log_message  VARCHAR2(4000),
    session_id   VARCHAR2(50)
        DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

CREATE TABLE demo_employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    salary NUMBER(10,2),
    commission_pct NUMBER(5,2)
);

INSERT INTO demo_employees VALUES (1, 'Ion', 'Ion', 3000, 0.10);
INSERT INTO demo_employees VALUES (2, 'Ana', 'Pop', 3500, NULL);
INSERT INTO demo_employees VALUES (3, 'Maria', 'Ionescu', 4000, 0.15);
INSERT INTO demo_employees VALUES (4, 'Vasile', 'Rusu', 2800, NULL);

COMMIT;

CREATE OR REPLACE PACKAGE debug_util IS

    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug;

    PROCEDURE disable_debug;

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2 DEFAULT 'INFO'
    );

    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    );

    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_line IN NUMBER,
        p_err  IN VARCHAR2
    );

END debug_util;
/

CREATE OR REPLACE PACKAGE BODY debug_util IS

    PROCEDURE write_log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2
    )
    IS
        PRAGMA AUTONOMOUS_TRANSACTION;
        v_level debug_log.log_level%TYPE;
    BEGIN
        v_level := UPPER(NVL(TRIM(p_level), 'INFO'));

        IF v_level NOT IN ('DEBUG', 'INFO', 'WARN', 'ERROR') THEN
            v_level := 'INFO';
        END IF;

        INSERT INTO debug_log (
            module_name,
            line_no,
            log_level,
            log_message
        )
        VALUES (
            SUBSTR(p_module_name, 1, 100),
            p_line,
            v_level,
            SUBSTR(p_message, 1, 4000)
        );

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
    END write_log;


    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;

        write_log(
            p_module_name => 'DEBUG_UTIL',
            p_line        => 1,
            p_message     => 'Debug mode enabled.',
            p_level       => 'INFO'
        );
    END enable_debug;


    PROCEDURE disable_debug IS
    BEGIN
        write_log(
            p_module_name => 'DEBUG_UTIL',
            p_line        => 2,
            p_message     => 'Debug mode disabled.',
            p_level       => 'INFO'
        );

        g_debug_mode := FALSE;
    END disable_debug;


    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_level       IN VARCHAR2 DEFAULT 'INFO'
    )
    IS
    BEGIN
        IF g_debug_mode THEN
            write_log(
                p_module_name => p_module_name,
                p_line        => p_line,
                p_message     => p_message,
                p_level       => p_level
            );
        END IF;
    END log;


    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    )
    IS
    BEGIN
        IF g_debug_mode THEN
            write_log(
                p_module_name => p_module_name,
                p_line        => p_line,
                p_message     => p_name || ' = ' || NVL(p_value, 'NULL'),
                p_level       => 'DEBUG'
            );
        END IF;
    END log_variable;


    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_line IN NUMBER,
        p_err  IN VARCHAR2
    )
    IS
    BEGIN
        write_log(
            p_module_name => p_proc,
            p_line        => p_line,
            p_message     => p_err,
            p_level       => 'ERROR'
        );
    END log_error;

END debug_util;
/


SHOW ERRORS PACKAGE debug_util;
SHOW ERRORS PACKAGE BODY debug_util;

/*
TASK 1 created:
    - DEBUG_LOG table
    - DEBUG_UTIL package
    - Enable/disable functionality
    - Message, variable, and error logging
    - Logging levels
TASK 2 now uses this framework inside a salary adjustment procedure.
*/


CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission
IS
    CURSOR c_employees IS
        SELECT employee_id,
               salary,
               commission_pct
        FROM demo_employees
        FOR UPDATE OF salary;

    v_new_salary demo_employees.salary%TYPE;
    v_increase   demo_employees.salary%TYPE;
    v_updated    PLS_INTEGER := 0;

BEGIN
    debug_util.log(
        p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
        p_line        => 1,
        p_message     => 'Procedure started.',
        p_level       => 'INFO'
    );

    FOR employee_rec IN c_employees LOOP

        debug_util.log(
            p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line        => 2,
            p_message     => 'Reading employee ID ' ||
                             employee_rec.employee_id || '.',
            p_level       => 'DEBUG'
        );

        debug_util.log_variable(
            p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line        => 3,
            p_name        => 'Current salary',
            p_value       => TO_CHAR(employee_rec.salary)
        );

        debug_util.log_variable(
            p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line        => 4,
            p_name        => 'Commission percentage',
            p_value       => TO_CHAR(employee_rec.commission_pct)
        );

        IF employee_rec.commission_pct IS NOT NULL THEN

            v_increase :=
                employee_rec.salary * employee_rec.commission_pct;

            v_new_salary :=
                employee_rec.salary + v_increase;

            debug_util.log(
                p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
                p_line        => 5,
                p_message     => 'Commission exists. Salary increased by ' ||
                                 TO_CHAR(v_increase) || '.',
                p_level       => 'INFO'
            );

        ELSE
            v_increase :=
                employee_rec.salary * 0.02;

            v_new_salary :=
                employee_rec.salary + v_increase;

            debug_util.log(
                p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
                p_line        => 6,
                p_message     => 'Commission is NULL. Default 2% increase ' ||
                                 'applied.',
                p_level       => 'INFO'
            );
        END IF;

        debug_util.log_variable(
            p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line        => 7,
            p_name        => 'Calculated new salary',
            p_value       => TO_CHAR(v_new_salary)
        );

        UPDATE demo_employees
        SET salary = ROUND(v_new_salary, 2)
        WHERE CURRENT OF c_employees;

        v_updated := v_updated + SQL%ROWCOUNT;

        debug_util.log(
            p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line        => 8,
            p_message     => 'Salary updated for employee ID ' ||
                             employee_rec.employee_id || '.',
            p_level       => 'DEBUG'
        );

    END LOOP;

    COMMIT;

    debug_util.log(
        p_module_name => 'ADJUST_SALARIES_BY_COMMISSION',
        p_line        => 9,
        p_message     => 'Procedure completed successfully. Employees updated: ' ||
                         v_updated || '.',
        p_level       => 'INFO'
    );

    DBMS_OUTPUT.PUT_LINE(
        'Salary adjustment completed. Employees updated: ' || v_updated
    );

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        debug_util.log_error(
            p_proc => 'ADJUST_SALARIES_BY_COMMISSION',
            p_line => 10,
            p_err  => 'SQLCODE=' || SQLCODE || '; SQLERRM=' || SQLERRM ||
                      '; BACKTRACE=' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
        );

        RAISE;
END adjust_salaries_by_commission;
/

/*
Explanation:
The procedure reads every employee using an explicit cursor.

For each employee:
    1. It logs that the employee was read.
    2. It logs the current salary and commission percentage.
    3. If COMMISSION_PCT is not NULL, it increases the salary proportionally.
    4. If COMMISSION_PCT is NULL, it increases the salary by 2%.
    5. It updates the current row.
    6. It records the update in DEBUG_LOG.

The salary is rounded to two decimal places.

If the procedure succeeds, it commits all salary updates.
If an error occurs, it rolls back all salary updates, records the error, and
raises the exception again.
*/

SHOW ERRORS PROCEDURE adjust_salaries_by_commission;


DELETE FROM debug_log;
COMMIT;


BEGIN
    debug_util.enable_debug;
    DBMS_OUTPUT.PUT_LINE('Debug mode is active.');
END;
/


BEGIN
    adjust_salaries_by_commission;
END;
/

---DISPLAY THE GENERATED DEBUG LOG


SELECT log_id,
       log_time,
       module_name,
       line_no,
       log_level,
       log_message,
       session_id
FROM debug_log
ORDER BY log_id;

--- DISPLAY UPDATED EMPLOYEE SALARIES

SELECT employee_id,
       first_name,
       last_name,
       salary,
       commission_pct
FROM demo_employees
ORDER BY employee_id;

