SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE demo_employees PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE demo_employees (
    employee_id    NUMBER PRIMARY KEY,
    first_name     VARCHAR2(50),
    last_name      VARCHAR2(50),
    salary         NUMBER(10,2),
    commission_pct NUMBER(5,2)
);

INSERT INTO demo_employees VALUES (1, 'Ion', 'Ion', 3000, 0.10);
INSERT INTO demo_employees VALUES (2, 'Ana', 'Pop', 3500, NULL);
INSERT INTO demo_employees VALUES (3, 'Maria', 'Ionescu', 4000, 0.15);
INSERT INTO demo_employees VALUES (4, 'Vasile', 'Rusu', 2800, NULL);

COMMIT;

--This section creates a simple employee table and inserts test data. Employees with a commission have a value in COMMISSION_PCT.
--Employees without a commission have NULL.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE debug_log PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE debug_log (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR2(100),
    message     VARCHAR2(400),
    log_date    DATE DEFAULT SYSDATE
);


--This table stores the debugging messages. It records the module name, the message, and the date.


CREATE OR REPLACE PACKAGE debug_util IS
    g_debug BOOLEAN := FALSE;

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log(
        p_module  VARCHAR2,
        p_message VARCHAR2
    );
END debug_util;
/


--The package specification declares the debug flag and the public procedures.

CREATE OR REPLACE PACKAGE BODY debug_util IS

    PROCEDURE enable_debug IS
    BEGIN
        g_debug := TRUE;
    END enable_debug;

    PROCEDURE disable_debug IS
    BEGIN
        g_debug := FALSE;
    END disable_debug;

    PROCEDURE log(
        p_module  VARCHAR2,
        p_message VARCHAR2
    )
    IS
    BEGIN
        IF g_debug THEN
            INSERT INTO debug_log(module_name, message)
            VALUES (p_module, p_message);
        END IF;
    END log;

END debug_util;
/


--The package body implements the procedures. Messages are inserted only when G_DEBUG is TRUE.

CREATE OR REPLACE PROCEDURE adjust_salary
IS
BEGIN
    debug_util.log('ADJUST_SALARY', 'Procedure started');

    UPDATE demo_employees
    SET salary =
        CASE
            WHEN commission_pct IS NOT NULL
                THEN salary + salary * commission_pct
            ELSE salary * 1.02
        END;

    debug_util.log('ADJUST_SALARY', 'Salaries updated');

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        debug_util.log('ADJUST_SALARY', SQLERRM);
        ROLLBACK;
END adjust_salary;
/

/*
This procedure updates all salaries.
COMMISSION_PCT not NULL -> salary = salary + salary * commission_pct
COMMISSION_PCT NULL -> salary = salary + 2%
The procedure also writes messages into DEBUG_LOG when debugging is active.
*/


BEGIN
    debug_util.enable_debug;
    adjust_salary;
    debug_util.disable_debug;
END;
/

--This block enables debugging, runs the salary procedure, and disables debugging.

SELECT * FROM demo_employees ORDER BY employee_id;

--This query displays the updated employee salaries.

SELECT * FROM debug_log ORDER BY id;

--This query displays the messages generated by the debugging package.
