
SET SERVEROUTPUT ON;

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    job_title VARCHAR2(100),
    employee_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT ck_employees_status
        CHECK (employee_status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    project_name VARCHAR2(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    project_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (project_id),
    CONSTRAINT uq_projects_name UNIQUE (project_name),
    CONSTRAINT ck_projects_dates
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_projects_status
        CHECK (project_status IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE tasks (
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    project_id NUMBER NOT NULL,
    task_name VARCHAR2(150) NOT NULL,
    task_status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    estimated_hours NUMBER(6,2),
    CONSTRAINT pk_tasks PRIMARY KEY (task_id),
    CONSTRAINT fk_tasks_project
        FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT ck_tasks_status
        CHECK (task_status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_tasks_hours
        CHECK (estimated_hours IS NULL OR estimated_hours >= 0)
);

CREATE TABLE timesheets (
    timesheet_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    timesheet_status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    CONSTRAINT pk_timesheets PRIMARY KEY (timesheet_id),
    CONSTRAINT fk_timesheets_employee
        FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT uq_timesheets_employee_period
        UNIQUE (employee_id, period_start, period_end),
    CONSTRAINT ck_timesheets_dates
        CHECK (period_end >= period_start),
    CONSTRAINT ck_timesheets_status
        CHECK (timesheet_status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE timesheet_entries (
    entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    timesheet_id NUMBER NOT NULL,
    task_id NUMBER NOT NULL,
    work_date DATE NOT NULL,
    hours_worked NUMBER(5,2) NOT NULL,
    work_description VARCHAR2(500),
    entry_details CLOB,
    CONSTRAINT pk_timesheet_entries PRIMARY KEY (entry_id),
    CONSTRAINT fk_entries_timesheet
        FOREIGN KEY (timesheet_id) REFERENCES timesheets(timesheet_id),
    CONSTRAINT fk_entries_task
        FOREIGN KEY (task_id) REFERENCES tasks(task_id),
    CONSTRAINT ck_entries_hours
        CHECK (hours_worked > 0 AND hours_worked <= 24),
    CONSTRAINT ck_entries_json
        CHECK (entry_details IS JSON)
);

CREATE INDEX idx_employees_last_name ON employees(last_name);
CREATE INDEX idx_projects_status ON projects(project_status);
CREATE INDEX idx_tasks_name ON tasks(task_name);
CREATE INDEX idx_timesheets_period_start ON timesheets(period_start);
CREATE INDEX idx_entries_work_date ON timesheet_entries(work_date);


INSERT INTO employees (first_name, last_name, email, job_title, employee_status)
VALUES ('George', 'George', 'george@example.com', 'Developer', 'ACTIVE'); 
INSERT INTO employees (first_name, last_name, email, job_title, employee_status)
VALUES ('Maria', 'Maria', 'maria@example.com', 'Tester', 'ACTIVE');
INSERT INTO employees (first_name, last_name, email, job_title, employee_status)
VALUES ('Ion', 'Ion', 'ion@example.com', 'Manager', 'ACTIVE');
INSERT INTO employees (first_name, last_name, email, job_title, employee_status)
VALUES ('Ana', 'Ana', 'ana@example.com', 'Developer', 'INACTIVE');

INSERT INTO projects (project_name, start_date, end_date, project_status)
VALUES ('Website', DATE '2026-01-01', DATE '2026-06-30', 'COMPLETED');
INSERT INTO projects (project_name, start_date, end_date, project_status)
VALUES ('Mobile App', DATE '2026-02-01', NULL, 'ACTIVE');
INSERT INTO projects (project_name, start_date, end_date, project_status)
VALUES ('Internal Tool', DATE '2026-03-01', NULL, 'ACTIVE');

INSERT INTO tasks (project_id, task_name, task_status, estimated_hours)
VALUES (1, 'Database', 'COMPLETED', 20);
INSERT INTO tasks (project_id, task_name, task_status, estimated_hours)
VALUES (1, 'Frontend', 'COMPLETED', 30);
INSERT INTO tasks (project_id, task_name, task_status, estimated_hours)
VALUES (2, 'Login', 'IN_PROGRESS', 15);
INSERT INTO tasks (project_id, task_name, task_status, estimated_hours)
VALUES (2, 'Reports', 'OPEN', 25);
INSERT INTO tasks (project_id, task_name, task_status, estimated_hours)
VALUES (3, 'Setup', 'OPEN', 10);

INSERT INTO timesheets (employee_id, period_start, period_end, timesheet_status)
VALUES (1, DATE '2026-05-01', DATE '2026-05-07', 'APPROVED');
INSERT INTO timesheets (employee_id, period_start, period_end, timesheet_status)
VALUES (2, DATE '2026-05-01', DATE '2026-05-07', 'SUBMITTED');
INSERT INTO timesheets (employee_id, period_start, period_end, timesheet_status)
VALUES (3, DATE '2026-05-01', DATE '2026-05-07', 'DRAFT');
INSERT INTO timesheets (employee_id, period_start, period_end, timesheet_status)
VALUES (1, DATE '2026-05-08', DATE '2026-05-14', 'APPROVED');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(1, 1, DATE '2026-05-01', 8, 'Database work','{"location":"office","device":"laptop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(1, 2, DATE '2026-05-02', 7, 'Frontend work','{"location":"home","device":"desktop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(2, 3, DATE '2026-05-01', 6, 'Login testing','{"location":"office","device":"laptop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(2, 4, DATE '2026-05-03', 5, 'Report testing','{"location":"home","device":"laptop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(3, 5, DATE '2026-05-04', 4, 'Project setup','{"location":"office","device":"desktop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(4, 3, DATE '2026-05-08', 8, 'Login development','{"location":"home","device":"laptop"}');
INSERT INTO timesheet_entries
(timesheet_id, task_id, work_date, hours_worked, work_description, entry_details)
VALUES
(4, 4, DATE '2026-05-09', 6, 'Reports development','{"location":"office","device":"desktop"}');

COMMIT;

CREATE OR REPLACE VIEW vw_employee_hours AS
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    NVL(SUM(te.hours_worked), 0) AS total_hours
FROM employees e
LEFT JOIN timesheets ts
    ON ts.employee_id = e.employee_id
LEFT JOIN timesheet_entries te
    ON te.timesheet_id = ts.timesheet_id
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name;

SELECT * FROM vw_employee_hours;

CREATE MATERIALIZED VIEW mv_project_hours
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    p.project_id,
    p.project_name,
    NVL(SUM(te.hours_worked), 0) AS total_hours
FROM projects p
LEFT JOIN tasks t
    ON t.project_id = p.project_id
LEFT JOIN timesheet_entries te
    ON te.task_id = t.task_id
GROUP BY
    p.project_id,
    p.project_name;

SELECT * FROM mv_project_hours;

-- Displays all employees stored in the database.
SELECT
    employee_id,
    first_name,
    last_name,
    email,
    job_title,
    employee_status
FROM employees
ORDER BY employee_id;

-- Displays all projects and their current status.
SELECT
    project_id,
    project_name,
    start_date,
    end_date,
    project_status
FROM projects
ORDER BY project_id;

-- Calculates the total number of worked hours for each employee using GROUP BY.
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    SUM(te.hours_worked) AS total_hours
FROM employees e
JOIN timesheets ts
    ON ts.employee_id = e.employee_id
JOIN timesheet_entries te
    ON te.timesheet_id = ts.timesheet_id
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY total_hours DESC;

-- Displays all employees, including employees who do not have a timesheet, using LEFT JOIN.
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    ts.timesheet_id,
    ts.period_start,
    ts.period_end,
    ts.timesheet_status
FROM employees e
LEFT JOIN timesheets ts
    ON ts.employee_id = e.employee_id
ORDER BY
    e.employee_id,
    ts.period_start;

-- Compares each entry with the average hours for the same project using an analytic function.
SELECT
    p.project_name,
    t.task_name,
    te.work_date,
    te.hours_worked,
    ROUND(
        AVG(te.hours_worked) OVER (PARTITION BY p.project_id),
        2
    ) AS average_project_hours
FROM timesheet_entries te
JOIN tasks t
    ON t.task_id = te.task_id
JOIN projects p
    ON p.project_id = t.project_id
ORDER BY
    p.project_name,
    te.work_date;


